### ISSUE TITLE
Can't install via npm on heroku...

### ISSUE THREAD

**Issue by bramski** [angularjs-oauth/oauth-ng#133]
```
remote: 63186 verbose stack Error: oauth-ng@0.4.10 postinstall: `bower install`
remote: 63186 verbose stack spawn ENOENT
remote: 63186 verbose stack     at ChildProcess.<anonymous> (/tmp/build_8208bc32284a657aafcdea79802d8d45/vendor/node/lib/node_modules/npm/lib/utils/spawn.js:17:16)
remote: 63186 verbose stack     at emitTwo (events.js:100:13)
remote: 63186 verbose stack     at ChildProcess.emit (events.js:185:7)
remote: 63186 verbose stack     at maybeClose (internal/child_process.js:850:16)
remote: 63186 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
remote: 63187 verbose pkgid oauth-ng@0.4.10
remote: 63188 verbose cwd /tmp/build_8208bc32284a657aafcdea79802d8d45
remote: 63189 error Linux 3.13.0-85-generic
remote: 63190 error argv "/tmp/build_8208bc32284a657aafcdea79802d8d45/vendor/node/bin/node" "/tmp/build_8208bc32284a657aafcdea79802d8d45/vendor/node/bin/npm" "install" "--userconfig" "/tmp/build_8208bc32284a657aafcdea79802d8d45/.npmrc" "--production"
remote: 63191 error node v5.11.1
remote: 63192 error npm  v3.8.6
remote: 63193 error file sh
remote: 63194 error code ELIFECYCLE
remote: 63195 error errno ENOENT
remote: 63196 error syscall spawn
remote: 63197 error oauth-ng@0.4.10 postinstall: `bower install`
remote: 63197 error spawn ENOENT
remote: 63198 error Failed at the oauth-ng@0.4.10 postinstall script 'bower install'.
remote: 63198 error Make sure you have the latest version of node.js and npm installed.
remote: 63198 error If you do, this is most likely a problem with the oauth-ng package,
remote: 63198 error not with npm itself.
remote: 63198 error Tell the author that this fails on your system:
remote: 63198 error     bower install
remote: 63198 error You can get information on how to open an issue for this project with:
remote: 63198 error     npm bugs oauth-ng
remote: 63198 error Or if that isn't available, you can get their info via:
remote: 63198 error     npm owner ls oauth-ng
remote: 63198 error There is likely additional logging output above.
```

**Comment by bramski** [comment]
Fixed by: https://github.com/angularjs-oauth/oauth-ng/pull/134

**Comment by dellinger** [comment]
But there isn't a current release with this fix -- is there a timeline?
